import { v4 as uuid } from 'uuid'

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

//  export const products = [
//   {
//     _id: uuid(),
//     title: "You Can WIN",
//     author: "Shiv Khera",
//     price: "5000",
//     categoryName: "non-fiction",
//   },
//   {
//     _id: uuid(),
//     title: "You are Winner",
//     author: "Junaid Qureshi",
//     price: "3000",
//     categoryName: "horror",
//   },
//   {
//     _id: uuid(),
//     title: "Think and Grow Rich",
//     author: "Shiv Khera",
//     price: "1000",
//     categoryName: "fiction",
//   },
// ];
export const products = [
    {
        _id: uuid(),
        name: 'Martini Exhaust',
        image: 'https://drive.google.com/uc?export=view&id=1gfAEXFUU7x2rrOadMVbb0OnsiU56KQcB',
        price: '5000.00',
        brand: 'X-Hosts',
        categoryName: 'Exhausts',
        inStock: true,
        fastDelivery: true,
        ratings: 4.5,
        offer: 'Republic Day Sale',
        idealFor: 'Men',
        maxQuantity: 20,
    },
    {
        _id: uuid(),
        name: 'GodZilla Exhaust',
        image: 'https://drive.google.com/uc?export=view&id=106v6RYa0KQY52TxWJcH4oc401vpEDI3k',
        price: '4500.00',
        brand: 'X-Hosts',
        categoryName: 'Exhausts',
        inStock: false,
        comingSoon: true,
        fastDelivery: false,
        ratings: 4.3,
        offer: 'Republic Day Sale',
        idealFor: 'Men',
        maxQuantity: 0,
    },
    {
        _id: uuid(),
        name: 'Squash Exhaust',
        image: 'https://drive.google.com/uc?export=view&id=13dxUWIpqAsTo1XaBtoKl0liWEGLSqM4j',
        price: '2500.00',
        brand: 'X-Hosts',
        categoryName: 'Exhausts',
        inStock: true,
        fastDelivery: false,
        ratings: 4,
        offer: '70% bonanza',
        idealFor: 'Senior',
        maxQuantity: 15,
    },
    {
        _id: uuid(),
        name: 'BlueMoon Wrap',
        image: 'https://drive.google.com/uc?export=view&id=1Uqk7GTnVEyyy6efBYA2VzvBtClJXV-95',
        price: '1200.00',
        brand: 'Wrapofy',
        categoryName: 'Wraps',
        inStock: true,
        fastDelivery: false,
        ratings: 3.7,
        offer: 'Republic Day Sale',
        idealFor: 'Girl',
        maxQuantity: 8,
    },
    {
        _id: uuid(),
        name: 'WalkerBlack Wrap',
        image: 'https://drive.google.com/uc?export=view&id=1z66GHkpxBIVeXQyEm72UyCILB6TEFQ63',
        price: '1500.00',
        brand: 'Wrapofy',
        categoryName: 'Wraps',
        inStock: true,
        fastDelivery: false,
        ratings: 4.7,
        offer: 'Save 50',
        idealFor: 'Men',
        maxQuantity: 5,
    },
    {
        _id: uuid(),
        name: 'Milky White',
        image: 'https://drive.google.com/uc?export=view&id=1xzNrT_byLHpbWcJkBwAsDoXbYNBwSKEo',
        price: '1200.00',
        brand: 'Wrapofy',
        categoryName: 'Wraps',
        inStock: false,
        comingSoon: false,
        fastDelivery: false,
        ratings: 4.2,
        offer: 'Republic Day Sale',
        idealFor: 'Men',
        maxQuantity: 0,
    },
    {
        _id: uuid(),
        name: 'Ironman Red',
        image: 'https://drive.google.com/uc?export=view&id=1uYqSlMJpLuiJXdTBuFVEij32eLPiTyhd',
        price: '2300.00',
        brand: 'Wrapofy',
        categoryName: 'Wraps',
        inStock: true,
        fastDelivery: true,
        ratings: 4.8,
        offer: '70% bonanza',
        idealFor: 'Boys',
        maxQuantity: 10,
    },
    {
        _id: uuid(),
        name: 'FingerPrint Sensors',
        image: 'https://drive.google.com/uc?export=view&id=17SNSOS80gdaHVrx9UyfFGn5nQ3BE_MTY',
        price: '8000.00',
        brand: 'Safers',
        categoryName: 'Safety',
        inStock: true,
        fastDelivery: false,
        ratings: 4.25,
        offer: '70% bonanza',
        idealFor: 'Senior',
        maxQuantity: 4,
    },
    {
        _id: uuid(),
        name: 'FireProof Doors',
        image: 'https://drive.google.com/uc?export=view&id=16E4Bfi0Z1YhtpdoCRRFY6jSAzmvTdGUe',
        price: '8000.00',
        brand: 'Safers',
        categoryName: 'Safety',
        inStock: false,
        comingSoon: true,
        fastDelivery: true,
        ratings: 4.3,
        offer: 'Save 50',
        idealFor: 'All',
        maxQuantity: 0,
    },
    {
        _id: uuid(),
        name: 'Funky Covers',
        image: 'https://drive.google.com/uc?export=view&id=1i0cHzjVlmC4VWX2in7fgRh5WE85Kga6J',
        price: '400.00',
        brand: 'Keyos',
        categoryName: 'Accessories',
        inStock: true,
        fastDelivery: true,
        ratings: 3.8,
        offer: 'Republic Day Sale',
        idealFor: 'Boy',
        maxQuantity: 30,
    },
    {
        _id: uuid(),
        name: 'Lambo Badge',
        image: 'https://drive.google.com/uc?export=view&id=1htdcUgHT5XDOZSU4fq95TaihUQHtL_mU',
        price: '230.00',
        brand: 'Keyos',
        categoryName: 'Accessories',
        inStock: true,
        fastDelivery: true,
        ratings: 3.5,
        offer: 'Republic Day Sale',
        idealFor: 'Boy',
        maxQuantity: 25,
    },
    {
        _id: uuid(),
        name: 'KingKong BodyKit',
        image: 'https://drive.google.com/uc?export=view&id=1M3sIUKdu8qpm0ZXUE8gDrjAaGTeRFDeZ',
        price: '9540.00',
        brand: 'Keyos',
        categoryName: 'Accessories',
        inStock: true,
        fastDelivery: false,
        ratings: 4.9,
        offer: 'Republic Day Sale',
        idealFor: 'Senior',
        maxQuantity: 2,
    },
    {
        _id: uuid(),
        name: 'Sausage Protector',
        image: 'https://drive.google.com/uc?export=view&id=1tQx0lIcR-YIumQvK098kR6zNxwQ6Vkkj',
        price: '2300.00',
        brand: 'Safers',
        categoryName: 'Safety',
        inStock: true,
        fastDelivery: true,
        ratings: 4,
        offer: '70% bonanza',
        idealFor: 'Men',
        maxQuantity: 6,
    },
    {
        _id: uuid(),
        name: 'Hype Spoiler',
        image: 'https://drive.google.com/uc?export=view&id=1uBLAxFV0OYvZCoXRv7eJKh47PTExqjUx',
        price: '2330.00',
        brand: 'X-Hosts',
        categoryName: 'Exhausts',
        inStock: true,
        fastDelivery: false,
        ratings: 3.6,
        offer: 'Republic Day Sale',
        idealFor: 'Senior',
        maxQuantity: 5,
    },
    {
        _id: uuid(),
        name: 'Fog Lamps',
        image: 'https://drive.google.com/uc?export=view&id=1lpo2GkWj07ZpBe-bfZ6JJbAbS6fjQ-e-',
        price: '2442.00',
        brand: 'Safers',
        categoryName: 'Safety',
        inStock: false,
        comingSoon: true,
        fastDelivery: true,
        ratings: 4.9,
        offer: 'Save 50',
        idealFor: 'All',
        maxQuantity: 0,
    },
    {
        _id: uuid(),
        name: 'Mammoth Spoiler',
        image: 'https://drive.google.com/uc?export=view&id=1Z13-95hgfz108GDfDW8cNAbtgRlBxabb',
        price: '2500.00',
        brand: 'X-Hosts',
        categoryName: 'Exhausts',
        inStock: false,
        comingSoon: true,
        fastDelivery: true,
        ratings: 4,
        offer: 'Republic Day Sale',
        idealFor: 'Men',
        maxQuantity: 5,
    },
    {
        _id: uuid(),
        name: 'Silky Grey',
        image: 'https://drive.google.com/uc?export=view&id=1_vDeBKn2lmCMpNR2kcmbql2Fa0Ai53t_',
        price: '1820.00',
        brand: 'Wrapofy',
        categoryName: 'Wraps',
        inStock: true,
        fastDelivery: true,
        ratings: 4.7,
        offer: '70% bonanza',
        idealFor: 'All',
        maxQuantity: 8,
    },
    {
        _id: uuid(),
        name: 'Leather Key Cover',
        image: 'https://drive.google.com/uc?export=view&id=16mll7qHkXZr2KxKd_Kqc-Ifhe61b5DsZ',
        price: '500.00',
        brand: 'keyos',
        categoryName: 'Accessories',
        inStock: false,
        comingSoon: false,
        fastDelivery: false,
        ratings: 3.2,
        offer: 'Save 50',
        idealFor: 'Men',
        maxQuantity: 0,
    },
]
